### ISSUE TITLE
执行到26/28步时报错：

### ISSUE THREAD

**Issue by goudanz** [repertory/docker-redash#2]
```
Step 26/28 : RUN node -v && npm -v &&     npm config set registry https://registry.npm.taobao.org &&     echo 'sass_binary_site=https://npm.taobao.org/mirrors/node-sass' >> ~/.npmrc &&     make &&     cp -r ./client/app/assets/fonts/roboto ./client/dist/fonts/ &&     rm -rf node_modules && npm cache clear
 ---> Running in a6807f4a7670
v6.10.3
3.10.10
if [ -d "./client/app" ]; then npm install; fi
npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.

[18256] Failed to execute script docker-compose
Traceback (most recent call last):
  File "http\client.py", line 546, in _get_chunk_left
  File "http\client.py", line 513, in _read_next_chunk_size
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "http\client.py", line 578, in _readinto_chunked
  File "http\client.py", line 548, in _get_chunk_left
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\response.py", line 362, in _error_catcher
  File "site-packages\urllib3\response.py", line 444, in read
  File "http\client.py", line 449, in read
  File "http\client.py", line 483, in readinto
  File "http\client.py", line 594, in _readinto_chunked
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 878, in run
  File "compose\cli\main.py", line 1333, in run_one_off_container
  File "compose\service.py", line 324, in create_container
  File "compose\service.py", line 360, in ensure_image_exists
  File "compose\service.py", line 1088, in build
  File "compose\progress_stream.py", line 25, in stream_output
  File "compose\utils.py", line 61, in split_buffer
  File "compose\utils.py", line 37, in stream_as_text
  File "site-packages\docker\api\client.py", line 345, in _stream_helper
  File "site-packages\urllib3\response.py", line 461, in read
  File "contextlib.py", line 99, in __exit__
  File "site-packages\urllib3\response.py", line 380, in _error_catcher
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by AnsonCong** [comment]
+1 同样的问题

**Comment by repertory** [comment]
@goudanz  @AnsonCong 

时间太久了，很多依赖包出现问题，等过段时间基于最新版再出个版本

先换成镜像地址吧  `registry.cn-hangzhou.aliyuncs.com/wangdong/redash:latest`

**Comment by loyaltylu** [comment]
镜像更新使用registry.cn-hangzhou.aliyuncs.com/wangdong/redash:latest也还卡在了26/28的步骤
